title: Nerfies
description: Deformable Neural Radiance Fields
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap 